In [2]:
import numpy as np

# Arrays

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [3]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print type(a)
print a.shape
print a[0], a[1], a[2]
print a.dtype
a[0] = 5                 # Change an element of the array
print a   

<type 'numpy.ndarray'>
(3,)
1 2 3
int64
[5 2 3]


In [4]:
b = np.array([[1,2,3],
              [4,5,6]])   # Create a rank 2 array
print type(b)
print b.shape
print b[0]
print b[0,0]
b[0][0]=5
print b

<type 'numpy.ndarray'>
(2, 3)
[1 2 3]
1
[[5 2 3]
 [4 5 6]]


In [5]:
c = np.array(1)
print type(c)
print c.shape
printc[0]
print c

<type 'numpy.ndarray'>
()


NameError: name 'printc' is not defined

# Reshape

In [6]:
b1 = b.reshape([6,])
print b1.shape
print b1

(6,)
[5 2 3 4 5 6]


In [7]:
b2 = b.reshape([6,1])
print b2.shape
print b2

(6, 1)
[[5]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [8]:
b3 = b.reshape([3,2,1])
print b3

[[[5]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]


# Array indexing


Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:

In [14]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print b

[[2 3]
 [6 7]]


In [16]:
row_r1 = a[0, :]    # Rank 1 view of the second row of a  
print row_r1

[1 2 3 4]


In [17]:
col_r1 = a[:, 0]
print col_r1


[1 5 9]


# Array math

In [28]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

# Elementwise sum; both produce the array
print x + y
print np.add(x, y)

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]]


In [29]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
print x + y
print np.add(x, y)

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
